version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "production"
    open-pull-requests-limit: 10
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: npm
    directory: /.storybook
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/common
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/hamburger-menu
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/portal-navigation
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/avatar-image
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /plugins/cem-preset
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /plugins/dev-helpers
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /plugins/markdown-storybook
    schedule:
      interval: daily
