name: Main Workflow

on: [push, pull_request]

jobs:
  # Run codestyle checks
  lint:
    name: Lint

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'

      - name: Dependencies
        run: npm ci

      - name: Linters
        run: npm run lint

  # Run tests
  test:
    name: Test

    runs-on: ubuntu-latest

    strategy:
      matrix:
#        node-version: [14.x, 16.x]
        node-version: [16.x]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Dependencies
        run: npm ci

      - name: Tests
        run: npm test

  # Build and deploy to Github Pages
  deploy:
    name: Deploy

    runs-on: ubuntu-latest

    needs: [lint, test]

    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'

      - name: Dependencies
        run: npm ci

      - name: Storybook Build
        run: npm run storybook:build

      # https://github.com/marketplace/actions/github-pages-action
      - name: Deploys
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./storybook-static
          allow_empty_commit: true
