name: Validate PR

on:
  pull_request:
    branches:
      - main
      - next

jobs:
  test:
    name: Lint & Test & Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      # @see https://www.voorhoede.nl/en/blog/super-fast-npm-install-on-github-actions/
      - uses: actions/cache@v2
        id: cache
        with:
          path: ./node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('package-lock.json') }}

      - name: Install packages
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Run postinstall
        if: steps.cache.outputs.cache-hit == 'true'
        run: npm run --if-present postinstall && npm rebuild && npm run prepare --if-present

      - name: Lint
        run: npm run lint

      - name: Test
        run: sudo npx playwright install-deps && npm run test:ci

      - name: Build
        run: npm run storybook:build

#  vrt:
#    name: Visual Regression Test
#    runs-on: macos-12
#    steps:
#      - uses: actions/checkout@v3
#      - uses: actions/setup-node@v3
#        with:
#          node-version: '16'
#
#      # @see https://www.voorhoede.nl/en/blog/super-fast-npm-install-on-github-actions/
#      - uses: actions/cache@v2
#        id: cache
#        with:
#          path: ./node_modules
#          key: ${{ runner.os }}-modules-${{ hashFiles('package-lock.json') }}
#
#      - name: Install packages
#        if: steps.cache.outputs.cache-hit != 'true'
#        run: npm ci
#
#      - name: Run postinstall
#        if: steps.cache.outputs.cache-hit == 'true'
#        run: npm run --if-present postinstall && npm rebuild && npm run prepare --if-present
#
#      - name: Test
#        run: npm run test:vrt
#
#      - name: Archive visual diff results
#        uses: actions/upload-artifact@v3
#        if: failure()
#        with:
#          name: visual-diffs
#          path: screenshots
#          retention-days: 7
