name: Validate PR

on:
  pull_request:
    branches:
      - main
      - next

permissions:
  contents: read

jobs:
  test:
    name: Lint & Test & Build
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
        with:
          egress-policy: audit

      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.8.1
        with:
          node-version: '18'

      # @see https://www.voorhoede.nl/en/blog/super-fast-npm-install-on-github-actions/
      - uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
        id: cache
        with:
          path: ./node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('package-lock.json') }}

      - name: Install packages
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Run postinstall
        if: steps.cache.outputs.cache-hit == 'true'
        run: npm run --if-present postinstall && npm rebuild && npm run prepare --if-present

      - name: Lint
        run: npm run lint

      - name: Test
        run: sudo npx playwright install-deps && npm run test:ci

      - name: Build
        run: npm run storybook:build

#  vrt:
#    name: Visual Regression Test
#    runs-on: macos-12
#    steps:
#      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
#      - uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.8.1
#        with:
#          node-version: '18'
#
#      # @see https://www.voorhoede.nl/en/blog/super-fast-npm-install-on-github-actions/
#      - uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
#        id: cache
#        with:
#          path: ./node_modules
#          key: ${{ runner.os }}-modules-${{ hashFiles('package-lock.json') }}
#
#      - name: Install packages
#        if: steps.cache.outputs.cache-hit != 'true'
#        run: npm ci
#
#      - name: Run postinstall
#        if: steps.cache.outputs.cache-hit == 'true'
#        run: npm run --if-present postinstall && npm rebuild && npm run prepare --if-present
#
#      - name: Test
#        run: npm run test:vrt
#
#      - name: Archive visual diff results
#        uses: actions/upload-artifact@v3
#        if: failure()
#        with:
#          name: visual-diffs
#          path: screenshots
#          retention-days: 7
