name: Visual Regression Tests

on:
  push:
    branches:
      - master
  pull_request:

# https://github.com/orgs/community/discussions/26681
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  vrt:
    name: Visual Regression Test
    runs-on: macos-12
    if: false
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          egress-policy: audit

      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4.0.0
        with:
          node-version: '18'

      # @see https://www.voorhoede.nl/en/blog/super-fast-npm-install-on-github-actions/
      - uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3.3.2
        id: cache
        with:
          path: ./node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('package-lock.json') }}

      - name: Install packages
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Run postinstall
        if: steps.cache.outputs.cache-hit == 'true'
        run: npm run --if-present postinstall && npm rebuild && npm run prepare --if-present

      - name: Test
        run: npm run test:vrt

      - name: Archive visual diff results
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
        if: failure()
        with:
          name: visual-diffs
          path: screenshots
          retention-days: 7
